name: Build webassembly
on:
  workflow_call:
    
env: 
  dotNetVersion: 8.0.x
  dotNetConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'true'
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
              dotnet-version: ${{ env.dotNetVersion }}
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: '21'
        - name: Install workloads
          run: dotnet workload restore 
        - name: npm install
          working-directory: Library
          run: npm install
        - name: Install dependencies
          working-directory: WebAssembly
          run: dotnet restore
        - name: .NET build
          working-directory: WebAssembly
          run: dotnet build -c ${{ env.dotNetConfiguration }}
        - name: .NET publish
          working-directory: WebAssembly
          run: dotnet publish -c ${{ env.dotNetConfiguration }}
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
              name: build
              path: WebAssembly/bin/Release/net8.0/publish/wwwroot
              retention-days: 1